name: Release Beta

on:
  push:
    branches: [ dev ]
jobs:
  release:
    needs:
      - "test"
      - "benchmarking"
      - "coding_standards_check"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
        
      
